---
- name: INSTALL | apple-superdrive
  tags:
    - install
  block:
    - name: INSTALL | Ensure sg3-utils is installed
      become: True
      ansible.builtin.apt:
        name: sg3-utils
        state: present

    - name: INSTALL | Ensure udev rule is present
      become: True
      notify: Trigger udevadm
      ansible.builtin.copy:
        src: 60-apple-superdrive.rules
        dest: /etc/udev/rules.d/60-apple-superdrive.rules
